services:
    webridge_oauth2_access.upstream_authenticator:
        class: Webridge\Oauth2AccessBundle\Services\UpstreamAuthenticator
        calls:
            - [setContainer, ["@service_container"]]

    webridge_oauth2_access.upstream_pre_authenticator:
        class:  Webridge\Oauth2AccessBundle\Services\SMGUserAuthenticator
        arguments: [ @webridge_oauth2_access.smg_user_proxy ]

    webridge_oauth2_access.smg_user_proxy:
        class:  Webridge\Oauth2AccessBundle\Services\SMGUserProxy
        public: false
        calls:
            - [setContainer, ["@service_container"]]
            - [configureRemoteEndpoints]
